name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.DEPLOY_GATSBY }}
      - name: Sending telegram notification 
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: |
            📢 !!
            Evento    : ${{ github.event_name }}
            Agente    : ${{ github.actor }}
            workflow  : ${{ github.workflow }}
            workspace : ${{ github.workspace }}
            Ha finalizado el proceso de manera satisfactoria! ✔✔
          